# tracking 관련 상수들 정의

# tracker 관련 상수들 정의
# 이럼 이제 맨 처음 정지되어있을때는 못잡을거임,, 랜덤임 음음음
# 최소 이동량(미터 단위 추정). 이보다 작으면 정지로 간주해 yaw 보정 생략
FORWARD_HEADING_MIN_DIST = 0.001
# 검출 yaw를 180° 주기로만 신뢰(앞/뒤 동일)하고, 이동 방향으로 부호를 고정하기 위한 파라미터
HEADING_LOCK_ANGLE_THR = 45.0
HEADING_UNLOCK_ANGLE_THR = 140.0
HEADING_LOCK_FRAMES = 2
HEADING_ALIGN_MIN_DIST = 0.001

# Kalman noise/variance tuning for smoother yet responsive tracks
POS_INIT_COV_SCALE = 250.0
POS_PROCESS_NOISE_SCALE = 1.0
POS_MEAS_NOISE_SCALE = 2.0
YAW_PROCESS_NOISE_SCALE = 0.05
YAW_MEAS_NOISE_SCALE = 0.5
SIZE_PROCESS_NOISE_SCALE = 0.01
SIZE_MEAS_NOISE_SCALE = 0.5
# 측정 업데이트 시 프레임 간격이 길어질수록 관측값 영향 줄이는 계수
MEAS_GAP_SMOOTH_FACTOR = 0.15

# History-based smoothing parameters
STATE_HISTORY_SIZE = 8
DEFAULT_SMOOTH_WINDOW = 5 # 최근 이만큼의 프레임을 반영해서 부드럽게 ㅇㅇ

# Tracking defaults and shared thresholds
DEFAULT_COLOR_LOCK_STREAK = 5
DEFAULT_MAX_AGE = 3 # 소멸되기 전까지 허용되는 최대 프레임 수
DEFAULT_MIN_HITS = 3 # 컨펌되기 위한 최소 히트 수
DEFAULT_IOU_THRESHOLD = 0.3
DEFAULT_COLOR_PENALTY = 0.3
YAW_PERIOD_DEG = 180.0
HEADING_FLIP_THRESHOLD = 90.0
KF_STATE_INIT_COV_SCALE = 10.0

# Class-specific tracker defaults
CAR_MAX_AGE = 5
CAR_MIN_HITS = 10
CAR_POS_PROCESS_NOISE = 2.0
CAR_POS_MEAS_NOISE = 1.5
CAR_YAW_PROCESS_NOISE = 0.08
CAR_YAW_MEAS_NOISE = 0.6
CAR_SIZE_PROCESS_NOISE = 0.02
CAR_SIZE_MEAS_NOISE = 0.6

OBSTACLE_MAX_AGE = 8
OBSTACLE_MIN_HITS = 4
OBSTACLE_POS_PROCESS_NOISE = 0.3
OBSTACLE_POS_MEAS_NOISE = 3.0
OBSTACLE_YAW_PROCESS_NOISE = 0.05
OBSTACLE_YAW_MEAS_NOISE = 1.2
OBSTACLE_SIZE_PROCESS_NOISE = 0.01
OBSTACLE_SIZE_MEAS_NOISE = 0.8
OBSTACLE_VEL_DAMPING = 0.35
OBSTACLE_OUTPUT_EMA_ALPHA = 0.45
OBSTACLE_JUMP_GATE_NORM_DIST = 6.0
OBSTACLE_OUTPUT_SNAP_EPS = 0.15
OBSTACLE_STOP_SPEED_THR = 0.15
OBSTACLE_STOP_FRAMES = 4
OBSTACLE_STOP_ALPHA_SCALE = 0.35
OBSTACLE_STOP_Q_SCALE = 0.35

CAR_OUTPUT_SNAP_EPS = 0.0
CAR_STOP_SPEED_THR = 0.0
CAR_STOP_FRAMES = 0
CAR_STOP_ALPHA_SCALE = 1.0
CAR_STOP_Q_SCALE = 1.0

ASSOC_CENTER_WEIGHT = 0.35
ASSOC_CENTER_NORM = 2.5

# fusion 관련 상수들 정의
# Fusion-related defaults
DIST_WEIGHT_D0 = 5.0
DIST_WEIGHT_P = 2.0
NORMALIZE_MAX_FRAC = 0.7
MIN_WEIGHT = 1e-6

# Robust weighting
CAUCHY_C = 2.385
WEIGHT_FLOOR = 1e-4
WEIGHT_MAX_CAM_FRAC = 0.65
LOC_SCALE_K = 1.4826
SIZE_SCALE_REL = 0.20
SCALE_MIN = 1e-3

# Angle handling
YAW_FLIP_THRESHOLD_DEG = 90.0
YAW_R_FALLBACK = 0.25

# cluster 관련 상수들 정의
IOU_CLUSTER_THR = 0.01
COLOR_BONUS = 0.0
COLOR_PENALTY = 0.0
